### ISSUE TITLE
Publish new version of `emdb`

### ISSUE THREAD

**Issue by targos** [cheminfo/mass-tools#137]
The one currently on npm still has openchemlib-utils@v2

**Comment by lpatiny** [comment]
In progress. We are trying to update to last lerna as well

**Comment by lpatiny** [comment]
Should be ok now but it was more difficult than expected and it took me a while to succeed. Reason is probably this bug in lerna. I had to remove a cyclic dependency to be able to publish:
- https://github.com/lerna/lerna/issues/3798
