### ISSUE TITLE
Can not publish with lerna

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/mass-tools#20]
https://github.com/cheminfo/mass-tools/runs/2096380850?check_suite_focus=true#step:9:45

Lerna does not have the credentials to publish the package

Before it was complaining that github was not configured and I added the following lines but this seems suspicious: 

https://github.com/cheminfo/mass-tools/blob/master/.github/workflows/release.yml#L31-L34

@targos Please could you help me ?

**Comment by targos** [comment]
The issue is that npm automation tokens do not work with the `whoami` endpoint that Lerna uses. It seems that a solution would be to run lerna with `--no-verify-access` so it doesn't call that endpoint before publishing.

**Comment by targos** [comment]
Ref: https://github.com/lerna/lerna/issues/2788

**Comment by lpatiny** [comment]
Great it works. Thanks !!
