### ISSUE TITLE
MF info properties untyped

### ISSUE THREAD

**Issue by stropitek** [cheminfo/mass-tools#226]
The 2 properties `monoisotopicMass` and `observedMonoisotopicMass` can exist on the `PartInfo` object but are not typed.

```ts
  const observedMass =
    // @ts-expect-error types are wrong in MF library
    (info.observedMonoisotopicMass || info.monoisotopicMass) as number;
```

**Comment by stropitek** [comment]
They are untyped because there is an option to override the property name to which the result is assigned.

https://github.com/cheminfo/mass-tools/blob/f663e61c0b8c6d27360d95b182204cf64cbf70cb/packages/mf-parser/src/util/getInfo.js#L27-L28

It is used by octochem.

https://github.com/search?q=org%3Acheminfo%20emFieldName&type=code

@lpatiny do you know the reason for this?

**Comment by lpatiny** [comment]
There is some history behind it and the fact that on one end I wanted to use 'short' properties names (em and mz) and on the other one a property name that means something (monoisotopicMass and observedMonoisotopicMass).

I think it will be time to make some big refactoring and breaking changes and only keep monoisotopicMass and observedMonoisotopicMass but I need to find the time to do it (a lot of implications).

**Comment by stropitek** [comment]
> Make the return type dynamically depend on these options?

I can try to do that, but I'm not very used to be defining types in jsdoc. I don't even know if it's possible.

**Comment by targos** [comment]
You can mix ts and js files in this project, and import from ts in the js doc if it easier for you

**Comment by lpatiny** [comment]
Could you just use the library with defining the type in your project for a while ? Because I would really prefer we make breaking changes rather than making complex types.

Same is true when fwhm = 0. We ned another function in this case so that the return type is constant.

You can open issues with all the inconsistencies in this library.

**Comment by stropitek** [comment]
> Could you just use the library with defining the type in your project for a while ?

We can ignore the type problem (it is what we do right now). But if we fix it, it's the same amount of work to fix it in the library so we'd better do that. If done with good type inference it would not force user to do something more complex at the typescript level when using the `getInfo` method.

**Comment by tpoisseau** [comment]
Closed by https://github.com/cheminfo/mass-tools/pull/241 (partial migration to typescript with advanced types)
