### ISSUE TITLE
Problem using the library in safari

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/mass-tools#69]
There is a problem in svg.js and we did a PR:

https://github.com/svgdotjs/svg.js/pull/1258

**Comment by targos** [comment]
You think that the functions in https://github.com/svgdotjs/svg.js/blob/master/src/modules/core/containerGeometry.js are not problematic after all?

**Comment by lpatiny** [comment]
Actually I can not reproduce this problem in safari with a simple case. Any idea about a small code that would trigger the error ?

**Comment by targos** [comment]
The Safari bug probably needs specific conditions to be triggered. I don't know how to test this.

**Comment by targos** [comment]
Closing as there's no reproduction
