### ISSUE TITLE
dependency cycle

### ISSUE THREAD

**Issue by targos** [cheminfo/mass-tools#70]
- [ ] emdb -> ms-spectrum -> emdb
  - add back `{ "path": "../emdb" }` to the tsconfig.json of ms-spectrum when fixed
- [x] mf-parser -> mf-utilities -> mf-parser

**Comment by tpoisseau** [comment]
https://github.com/acrazing/dpdm

```console
% npx dpdm --no-warning --no-tree circular packages/emdb/src/index.js
✔ [156/156] Analyze done!
• Circular Dependencies
  1) packages/ms-spectrum/lib/src/index.js -> packages/ms-spectrum/lib/src/Spectrum.js -> packages/ms-spectrum/lib/src/getFragmentPeaks.js -> packages/emdb/lib/src/index.js
```

**Comment by tpoisseau** [comment]
So it seems we need to solve this last circular deps between emdb and ms-spectrum

**Comment by tpoisseau** [comment]
Is it OK if I move `emdb#EMDB.prototype.fromMonoisotopicMass` to `ms-spectrum#fromMonoisotopicMass` ?

`ms-spectrum` depend on `emdb` only to do `emdb.fromMonoisotopicMass`

`emdb` depend on `ms-spectrum` to do `experimentalSpectrum.normedY()`, `this.experimentalSpectrum = new Spectrum(data, { threshold }), get `experimentalSpectrum.data` and `experimentalSpectrum.sumY()`

I can keep `fromMonoisotopicMass` in EMDB, but calling `ms-spectrum#fromMonoisotopicMass`.
Like that, emdb depend on ms-spectrum but ms-spectrum do not depend on emdb

**Comment by targos** [comment]
@lpatiny wdyt?

**Comment by lpatiny** [comment]
Yes seems ok to me as long as the API does not change and all the tests continue to pass (you will need somehow to duplicate some tests to test fromMonoisotopicMass in ms-spectrum and in emdb)
