### ISSUE TITLE
Update svgdom / svg.js fails

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/mass-tools#73]
Currently we can not update those 2 libraries as long as we didn't update our testcases

- svgdom
- svg.js

https://github.com/svgdotjs/svg.js/issues/1252

**Comment by lpatiny** [comment]
I think we should migrate to a react approach without svg libraries like in https://github.com/cheminfo/molecules-graph

**Comment by Fuzzyma** [comment]
Not sure, if still relevant but the issue is fixed on master now

**Comment by lpatiny** [comment]
Great many thanks !
